export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_ITEM = "INCREASE_ITEM"
export const DECREASE_ITEM = "DECREASE_ITEM"
export const CART_OPEN = "CART_OPEN"
export const CLEAR_CART = "CLEAR_CART"